#!/bin/bash

cmsStageIn /store/caf/user/ajkumar/apeSkim_10_1_Xra.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_11_1_rSm.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_12_1_nZD.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_13_1_34A.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_14_1_GUp.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_15_1_dn2.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_16_1_G64.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_17_1_g19.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_18_1_gkS.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_19_1_vi6.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_1_1_jHo.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_20_1_PTK.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_21_1_pGN.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_22_1_nCI.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_23_1_Aot.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_24_1_qjE.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_25_1_RKO.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_26_1_lFR.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_27_1_k7U.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_28_1_0Jj.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_29_1_qrB.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_2_1_kXB.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_30_1_Op1.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_31_1_w6J.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_32_1_DTf.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_33_1_QkP.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_34_1_qkj.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_35_1_MGs.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_36_1_fFF.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_37_1_vAW.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_38_1_prl.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_39_1_0D5.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_3_1_Zfj.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_4_1_yPg.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_5_1_ePg.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_6_1_8in.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_7_1_v3B.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_8_1_RMA.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_9_1_hW7.root .

