#!/bin/bash

cmsStageIn /store/caf/user/ajkumar/apeSkim_10_1_S3x.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_11_1_wTD.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_12_1_RFc.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_13_1_mbo.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_14_1_pwR.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_15_1_CJq.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_16_1_OVS.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_17_1_7sk.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_18_1_oq2.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_19_1_zSc.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_1_1_0X0.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_20_1_aEB.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_21_1_I9s.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_22_1_x74.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_23_1_11H.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_24_1_X1C.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_25_1_LPW.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_26_1_C20.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_27_1_cuf.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_28_1_fzy.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_29_1_pFW.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_2_1_QQQ.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_30_1_WG4.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_31_1_xPl.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_32_1_NdX.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_33_1_uih.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_34_1_oTM.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_35_1_OVa.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_36_1_RAR.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_37_1_VCW.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_38_1_3wg.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_39_1_CKc.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_3_1_vi6.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_4_1_7bg.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_5_1_Dps.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_6_1_or7.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_7_1_XRv.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_8_1_IGn.root .
cmsStageIn /store/caf/user/ajkumar/apeSkim_9_1_lET.root .
